export const GENERATION_TOKEN_COUNT_COOKIE = 'yFqHvvwJZ3yM0153Rml3H';
export const GENERATION_TOKEN_DAILY_LIMIT = 20;
export const GENERATION_TOKEN_RETENTION_HOURS = 24;
export const GENERATION_TOKEN_LIMIT_REACHED = 'GENERATION_TOKEN_LIMIT_REACHED';
export const EXTERNAL_ID_COOKIE = 'external_id';

export const IMAGE_HISTORY_COOKIE = '4aHWRtn_PhQKo4YZ38iKZ';
