export const GENERATION_TOKEN_COUNT_COOKIE = 'generationTokenCount';
export const GENERATION_TOKEN_DAILY_LIMIT = 20;
export const GENERATION_TOKEN_RETENTION_HOURS = 24;
export const GENERATION_TOKEN_LIMIT_REACHED = 'GENERATION_TOKEN_LIMIT_REACHED';
export const IS_CAPTCHA_VERIFIED = 'IS_CAPTCHA_VERIFIED';
