export const GENERATION_TOKEN_COUNT_COOKIE = 'yFqHvvwJZ3yM0153Rml3H';
export const GENERATION_TOKEN_DAILY_LIMIT = 20;
export const GENERATION_TOKEN_RETENTION_HOURS = 24;
export const GENERATION_TOKEN_LIMIT_REACHED = 'GENERATION_TOKEN_LIMIT_REACHED';

export const IMAGE_HISTORY_COOKIE = 'ppYdasH6PhxVpx6fe0H8A';
